name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.8"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Test
        run: ./test.sh --junitxml=junit/test-results.xml --cov=src --cov-report=xml --cov-report=html

      - name: Lint
        run: ./lint.sh

      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: junit/test-results.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
